### PR TITLE
Escape string values in sql

### PR DESCRIPTION
**Pull request by rmarianski**
@zerebubuth, @nvkelso: could you review please?

### CODE REVIEW

**Comment by nvkelso** [comment]
Does the Postgres library include this for us?

**Comment by rmarianski** [comment]
It doesn't, but I may be able to re-arrange things a little to have it escape the parameters when executing the statement itself. It seems like that's the recommended way to do it. I'll look into that.

**Comment by rmarianski** [comment]
I updated the sql command execution to use named query parameters. As a bonus, it simplified some of the code too.

**Comment by nvkelso** [comment]
Generally looks good. 

Why don't we need to set the SRID anymore?

**Comment by rmarianski** [comment]
We tell shapely to encode it in the wkb: https://github.com/mapzen/tilequeue/pull/50/files#diff-3c589dc895a7fd4ecd09a8c77c9cb336R561

**Comment by zerebubuth** [comment]
:+1: :zap:

Nice! Makes me wish I'd [RTFM](http://initd.org/psycopg/docs/usage.html#query-parameters)ed properly! :wink:

**Pull request merged**
