### PR TITLE
Update failure logging to stay on one line

### PR DESCRIPTION
**Pull request by rmarianski**
@zerebubuth: could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Good point! In case of other weird characters, might it be worth quoting the whole thing? Something like:

```python
logger.error('Neighbourhood failure for %s: %s - %s' % (
  failure.wof_id, repr(failure.reason), repr(failure_message)))
```

Then we can see when `reason` or the message might be `None` or have other, non-printable characters in them?

**Comment by rmarianski** [comment]
Good point. The `repr` formatting might give us some extra quotes, but that'll probably be more useful for debugging and safer too. Added in 2d15784.

**Comment by zerebubuth** [comment]
Ooh, `%r` is `repr`? That's cool, I didn't know that!

:+1:

**Comment by rmarianski** [comment]
Yup, `%r` is the equivalent of `repr`. It certainly looks like that locally anyway :)

**Pull request merged**
